id = "2"
question = "Is not God therefore merciful?"

[[sections]]
text = "Yea,Verily he is (þ) merciful 3 but (>, 
that heis also(q)just: wherefore his Justice 
Tequireth that the fame which is com- 
mitted against the divine Majesty of God, 
should also be xecompeniced with extream, | 


that is,everlasting Punishment both i in Bo- | 
dy and Soul. 


CG) Ex2d, 36 6. Psal, 8.455 6: od. Exod 20. 5, 


Cor. 6., þ 
; Q& S ecing then by the just Juduen 5 | 


en 
'nal Punishments,is there yet any way or means 


T- 


far. 
his 
nd 


nd - 


(5) 
God we are subjet both to temporal and eter- 


remaining whereby we may be delivered from 
these Punishments, and be reconciled to God? 

A. God will have his (2) Justice'fati(- 
fied: wherefore it is neceflary (b)that we 


satisfy either by our {clves,or by another. 
(4) Exod. 20. 5,5. and 23. 7. (6) Rom. 8. 3."
verses = ""

