id = "2"
question = "What rule has God given to direct us how we may glorify and enjoy Him?"

[[sections]]
text = "The Word of God, which is contained in the Scriptures of the Old and New Testaments,"
verses = "2 Timothy 3:16; Ephesians 2:20"

[[sections]]
text = "is the only rule to direct us how we may glorify and enjoy Him."
verses = "1 John 1:3; Isaiah 8:20"
