id = "2"
question = "How many things are necessary for you to know, that you enjoying this comfort may live and die happily?"

[[sections]]
text = "Three. The first: what is the"
verses = "Luke 24:47"

[[sections]]
text = "greatness of my sin and misery. The second, how I am"
verses = "Romans 7:24; Romans 8:15; Titus 3:3-5"

[[sections]]
text = "delivered from all my sin and misery. The third, what thanks"
verses = "John 17:3"

[[sections]]
text = "I owe unto God for this delivery."
verses = "Ephesians 5:10; 1 Peter 2:9; 1 Peter 3:10-11; Romans 9:11-13; Matthew 5:16; Titus 2:11-12"
