id = "3"
question = "What manner of Mediator then, and 
Deliverer must we seek for?"

[[sections]]
text = "Such a one verily as is very Man, 
and perfectly just,and yet in Power above 
all creatures,that is,one who also is yery 
TT OO 

Cf) 1Cor. 15. 25. Jer. 23-6. fa. 53. 11: 2 Cor? 
5: 14+ Heb. 7: 16, Ia. 3. 14. Rom, 8. 3. ++"
verses = ""

