id = "4"
question = "What does the Law of God require of us?"

[[sections]]
text = "That which Christ does summarily teach us, Matthew 22:37-40. You shall love the Lord your God with all your Heart, and with all your Soul, and with all your Mind, and with all your"
verses = "Luke 10:27"

[[sections]]
text = "Strength. This is the first and the great Commandment. And the second is like unto it, You shall love your Neighbour as yourself. On these two Commandments hang the whole Law and the Prophets."
verses = ""
