id = "4"
question = "Where- 


—— —— 


q & ) 4 
Q:. Wherefore is it necessary that he be very 
Man, and that perfefily just too?- '1"

[[sections]]
text = "Because that the Justice of God 're- 

quireth that the same humane nature * 
which hath s{inned.,do it. (elf. likewise make 


recompence for fin: but (g) he that is - 
himself a (b) sinner; cannot: make recom=- 


pence for others. -: 
" (g) Roni.'5, 124 19. (4)1 Per, 3.18, Heb. 9:26,"
verses = ""

