id = "5"
question = "Are you able to keep all these perfectly?"

[[sections]]
text = "No truly: for by nature I am"
verses = "Romans 3:10-23; 1 John 1:8"

[[sections]]
text = "prone to the hatred of God, and of my"
verses = "Romans 8:7; Ephesians 2:3; Titus 3:3"

[[sections]]
text = "Neighbours."
verses = ""
