id = "6"
question = "Did God then make man so wicked and perverse?"

[[sections]]
text = "Not so, but rather he made him good, and to his own"
verses = "Genesis 1:31"

[[sections]]
text = "Images that is, endued with true Righteousness and Holiness, that he might rightly know God his Creator, and heartily love him, and live with him blessed for ever, and that to laud and magnify"
verses = "Genesis 1:26,27"

[[sections]]
text = "him."
verses = "2 Corinthians 3:18; Colossians 3:10; Ephesians 4:24"
