id = "7"
question = "Whence then ariseth the wickedness of Mans nature?"

[[sections]]
text = "From the fall and disobedience of our first Parents Adam and"
verses = "Romans 5:12,18,19"

[[sections]]
text = "Eve: hence is our nature so corrupt that we are all conceived and born in"
verses = "Psalm 51:5; Genesis 5:3"

[[sections]]
text = "Sin."
verses = ""
