id = "8"
question = "What doth this knowledg of the Cre-- 


(10)"

[[sections]]
text = "That i in (n) adversity we may be 
patient(o),and thankful -in p:rosperity(p), 


| and have hercafter our chiefelt hope re- 


posed in God our most faithful Fatherzbe- 
ing sure that there is nothing which (q) 
may withdraw us from his lovezforasmuch 
as all creatures are (o in his Power, that 
without his Will they are (r) not able not 


only to do any thing, but not so much as 
Once to move. 


(z:) Rom, 5.3, Job. 21. (o) D2ut. 8. 10. 
T Theff. 5.18. (p) Rom, 5.4.5. &) Rom. 8. 


38, 19. (r) Job 1. 12. and 2. 6. Pro, 21. 1. Act, 
I 7. 27, &c."
verses = ""

