id = "9"
question = "Does not God then do injury to Man who in the Law requires that of him which he is not able to perform?"

[[sections]]
text = "No: For God had made Man such a one as"
verses = "John 3:5; Ephesians 4:24"

[[sections]]
text = "he might perform it: but Man by the impulse of the"
verses = "Luke 10:30"

[[sections]]
text = "Devil, and his own stubbornness bereaved himself and all his posterity of those Divine Graces."
verses = ""
