id = "9"
question = "Why is the Son of God called Fesus, 


that is, a Saviour?"

[[sections]]
text = "Because he saveth us from our ( s) 
sinszneither ought any fafety to be sought 


for from any other (t), nor can elsewhere 
be found. 


(-) Mat. 1. 21. [t] Heb. 7. 25, AAS. 4. 12. 


. Do they then believe in the only $ avi- 
our Fesus, who seek, for happiness and safety 
of the Saints, or of themselves, or else where? 

A. No: for although in word they boast 
themselves of him as their only Saviour, 
yet indeed they deny the only (a)Saviour 
Jesus: for it must needs be that either Jesus 
is not a perfedt Saviour,or chat those who. 
imbrace him as their Saviour with a true 


faith 


FT 
faith, possess all things in him (b) which 
are required unto Salvation. 
() 1 Cor. 1.13- and 3o, &c, (5) Heb. 12.2Â» 


Isa. 9: 6. Col. 1. 19, 20, and 2. 10. Ia, 43. 11. |}: 
26d $6. John, 1. 16.."
verses = ""

