id = "10"
question = "Does God leave this stubbornness and falling away of Man unpunished?"

[[sections]]
text = "No: but is angry in most dreadful"
verses = "Romans 5:12"

[[sections]]
text = "manner, as well for the sins wherein we are born, as also for those which our selves commit, and in most just Judgment punishes them with present and everlasting Punishments, as himself pronounces: Cursed be he that confirms not all the words of this Law to do"
verses = "Deuteronomy 27:26; Galatians 3:10"

[[sections]]
text = "them."
verses = ""
