id = "11"
question = "Is not God therefore merciful?"

[[sections]]
text = "Yes, truly he is"
verses = "Exodus 34:6; Psalm 5:4,5,6"

[[sections]]
text = "merciful; but so, that he is also"
verses = "Exodus 20:5; 2 Corinthians 6:14"

[[sections]]
text = "just: therefore his Justice requires that sin which is committed against the divine Majesty of God, should also be recompensed with extreme, that is, everlasting Punishment both in Body and Soul."
verses = ""
