id = "12"
question = "Are we able to satisfy by ourselves?"

[[sections]]
text = "Not at all. On the contrary, we do every day"
verses = "Job 9:2,3; Job 15:15; Matthew 6:12"

[[sections]]
text = "increase our debt."
verses = ""
