id = "14"
question = "Is there any creature in Heaven or in Earth, which is only a creature, able to satisfy for us?"

[[sections]]
text = "None. For first God will"
verses = "Psalm 130:3; Job 4:18; Job 25:5"

[[sections]]
text = "not punish that Sin in any other creature which man has committed: and further, neither can that which is nothing but a creature sustain the wrath of God against sin,"
verses = ""

[[sections]]
text = "and deliver others from it."
verses = ""
