id = "15"
question = "What manner of Mediator then, and Deliverer must we seek for?"

[[sections]]
text = "Such a one verily as is very Man, and perfectly just, and yet in Power above all creatures, that is, one who also is very"
verses = "1 Corinthians 15:25; Jeremiah 23:6; Isaiah 53:11; 2 Corinthians 5:14; Hebrews 7:16; Isaiah 7:14; Romans 8:3"

[[sections]]
text = "God."
verses = ""
