id = "15"
question = "Why is it necessary that he be very Man, and that perfectly just too?"

[[sections]]
text = "Because that the Justice of God requires that the same human nature which has sinned, do itself likewise make recompence for sin: but"
verses = "Romans 5:12,17"

[[sections]]
text = "he that is himself a"
verses = "1 Peter 3:18; Hebrews 7:26"

[[sections]]
text = "sinner, cannot make recompence for others."
verses = ""
