id = "16"
question = "Why must he also be very God?"

[[sections]]
text = "That he might by the Power of his"
verses = "Isaiah 55:3,8; Acts 2:24; 1 Peter 3:18"

[[sections]]
text = "Godhead sustain in his flesh the burthen of God's wrath,"
verses = "1 John 1:2; 1 John 4:9,10; Acts 20:28; John 3:16"

[[sections]]
text = "and might recover and restore unto us that Righteousness and Life which we lost."
verses = ""
