id = "18"
question = "And who is that Mediator which is together both very God, and a very perfectly just Man?"

[[sections]]
text = "Even our Lord Jesus"
verses = "Matthew 1:23; 1 Timothy 3:16; John 14:16; 1 Timothy 2:5; Luke 2:11"

[[sections]]
text = "Christ, who is made to us of God's Wisdom, Righteousness, Sanctification"
verses = "1 Corinthians 1:30"

[[sections]]
text = "& Redemption."
verses = ""
