id = "19"
question = "Is then Salvation restored by Christ to all men who perished in Adam?"

[[sections]]
text = "Not to all: but to those only who by a true Faith are ingrafted into him"
verses = "John 1:12; John 3:36; Isaiah 53:11; Psalm 2:12; Romans 11:20; Hebrews 4:2; Hebrews 10:39"

[[sections]]
text = "and receive his benefits."
verses = ""
