id = "19"
question = "From where do you know this?"

[[sections]]
text = "Out of the Gospel which God first made known"
verses = "Genesis 3:15"

[[sections]]
text = "in Paradise, and"
verses = "Genesis 22:18; Genesis 49:10,11; Romans 1:2; Hebrews 1:1; Acts 3:22; Acts 10:43"

[[sections]]
text = "afterwards did spread it a broad by the Patriarchs and"
verses = "John 5:46; Hebrews 10:7"

[[sections]]
text = "Prophets: shadowed it by Sacrifices and other Ceremonies of the Law; and"
verses = "Romans 10:4; Galatians 4:4; Hebrews 13:8"

[[sections]]
text = "lastly accomplished it by his only begotten Son Christ our Lord."
verses = ""
