id = "21"
question = "What is Faith?"

[[sections]]
text = "It is not only a knowledge, whereby I surely assent to all things which God"
verses = "Hebrews 11:13; James 2:19; Galatians 2:20"

[[sections]]
text = "has revealed unto us in his Word, but also an"
verses = "Romans 4:16; Romans 5:1; Romans 10:10"

[[sections]]
text = "assured trust kindled in"
verses = "Romans 1:16; Romans 10:17; 1 Corinthians 1:21; Mark 16:16; Acts 16:14"

[[sections]]
text = "my heart by the Holy Ghost, through the Gospel, whereby I make my repose in God, being assuredly resolved that: Remission of Sins, everlasting"
verses = "Matthew 16:17; John 3:5; Galatians 5:22; Philippians 1:19"

[[sections]]
text = "Righteousness, and life is given not to others only, but to me also, and that freely through the Mercy of God, for"
verses = "Romans 3:24,25; Acts 10:45"

[[sections]]
text = "the Merits of Christ alone."
verses = ""
