id = "23"
question = "Seeing there is but one only substance of God, why do you name those three, the Father, the Son, and the Holy Ghost?"

[[sections]]
text = "Because God"
verses = "Deuteronomy 6:4; Ephesians 4:6; Isaiah 44:6; Isaiah 45:5; 1 Corinthians 8:4"

[[sections]]
text = "has so manifested himself in his Word, that these three distinct Persons are that one true everlasting God."
verses = "Isaiah 61:1; Luke 4:18; Psalm 110:1; Matthew 3:16,17; Matthew 28:19; John 14:26; John 15:26; Titus 3:5,6; Ephesians 2:18; 2 Corinthians 13:14; Galatians 4:6; 1 John 5:7"
