id = "23"
question = "Into how many parts is this Creed divided?"

[[sections]]
text = "Into three: the first of the eternal Father, and our Creation: the second of the Son and our Redemption: the third of the Holy Ghost, and our Sanctification."
verses = ""
