id = "25"
question = "What do you believe when you say, I believe in God the Father Almighty, maker of Heaven and Earth?"

[[sections]]
text = "I believe the everlasting Father of our Lord Jesus Christ"
verses = "Genesis 1:1,2; Psalm 33:6; Job 33:4; Acts 4:24; Acts 14:15"

[[sections]]
text = "who made of nothing Heaven and Earth, with all that are in them; who likewise upholds"
verses = "Psalm 104:3; Psalm 115:3; Matthew 10:29; Hebrews 1:3; Romans 11:36"

[[sections]]
text = "and governs the same by his eternal Counsel and"
verses = "John 1:12; Romans 8:15; Galatians 4:5,6; Ephesians 1:5"

[[sections]]
text = "Providence. This God I believe to be my God and Father for Christ's sake; and therefore to trust in him, and rely on him, that I make no doubt but he will provide all"
verses = "Psalm 55:23; Matthew 6:26; Luke 12:22"

[[sections]]
text = "things necessary both for my soul and body; and further, whatsoever evils he sends on me in this troublesome life, he"
verses = "Romans 8:28"

[[sections]]
text = "will turn them to my safety; seeing both he is able to do it, as being"
verses = "Isaiah 46:4; Romans 10:12; Romans 8:38"

[[sections]]
text = "God Almighty, and willing to do it, as being a bountiful Father."
verses = ""
