id = "26"
question = "What does this knowledge of the Creation and Providence of God profit us?"

[[sections]]
text = "That in"
verses = "Romans 5:3; Job 1:21"

[[sections]]
text = "adversity we may be patient"
verses = "Deuteronomy 8:10; 1 Thessalonians 5:18"

[[sections]]
text = "and thankful in prosperity"
verses = "Romans 5:4,5"

[[sections]]
text = "and have our greatest hope placed in God our most faithful Father, being sure that there is nothing which"
verses = "Romans 8:38,39"

[[sections]]
text = "may withdraw us from his love; since all creatures are so in his Power, that without his Will they are"
verses = "Job 1:12; Job 2:6; Proverbs 21:1; Acts 17:27"

[[sections]]
text = "not able not only to do any thing, but not so much as once to move."
verses = ""
