id = "26"
question = "What is the Providence of God?"

[[sections]]
text = "The almighty Power of God, everywhere"
verses = "Acts 17:25; Psalm 94:9; Isaiah 29:15; Ezekiel 8:12"

[[sections]]
text = "present, whereby he does as it were by his hand uphold"
verses = "Hebrews 1:2,3"

[[sections]]
text = "and govern Heaven and Earth, with all the Creatures therein, so that those things which grow in the Earth, as likewise rain and drowth, fruitfulness and bareness, meat"
verses = "Jeremiah 5:24; Acts 14:17"

[[sections]]
text = "and"
verses = "John 9:3"

[[sections]]
text = "drink, health and"
verses = "Proverbs 22:2"

[[sections]]
text = "sickness, riches and poverty; in a word, all things come not rashly and by chance, but by his fatherly Counsel and Will."
verses = ""
