id = "27"
question = "Why is the Son of God called Jesus, that is, a Saviour?"

[[sections]]
text = "Because he saves us from our"
verses = "Matthew 1:21"

[[sections]]
text = "sins; neither ought any safety to be sought for from any other"
verses = "Hebrews 7:25; Acts 4:12"

[[sections]]
text = "nor can elsewhere be found."
verses = ""
