id = "29"
question = "Do they then believe in the only Saviour Jesus, who seek for happiness and safety of the Saints, or of themselves, or elsewhere?"

[[sections]]
text = "No: for although in word they boast themselves of Him as their only Saviour, yet indeed they deny the only"
verses = "1 Corinthians 1:13; 1 Corinthians 1:30"

[[sections]]
text = "Saviour Jesus: for it must needs be that either Jesus is not a perfect Saviour, or that those who embrace him as their Saviour with a true faith, possess all things in him"
verses = "Hebrews 12:2; Isaiah 9:6; Colossians 1:19,20; Colossians 2:10; Isaiah 43:11; John 1:16"

[[sections]]
text = "which are required unto Salvation."
verses = ""
