id = "30"
question = "Why is he called Christ, that is, anointed?"

[[sections]]
text = "Because he was ordained of the Father, and anointed of the holy Ghost"
verses = "Psalm 45:7; Hebrews 1:9; Deuteronomy 18:15; Acts 3:22"

[[sections]]
text = "the chief Prophet"
verses = "John 1:18; John 15:15; Matthew 11:27"

[[sections]]
text = "and Teacher, who"
verses = "Hebrews 7:21; Hebrews 10:12"

[[sections]]
text = "has opened unto us the secret Counsel, & all the will of his Father concerning our Redemption, and the high Priest, who with that one only Sacrifice of his Body"
verses = "Romans 3:24; Romans 5:9,10"

[[sections]]
text = "has redeemed us, and does"
verses = "Psalm 2:6; Luke 1:33"

[[sections]]
text = "continually make Intercession to his Father for us; and a King, who rules us by his Word and Spirit, and defends"
verses = "Matthew 28:18"

[[sections]]
text = "and maintains that Salvation which he has purchased for us."
verses = ""
