id = "31"
question = "For what cause is Christ called the only begotten Son of God, when we also are the Sons of God?"

[[sections]]
text = "Because Christ alone is the eternal and natural Son of the"
verses = "Hebrews 1:2,3; John 3:16"

[[sections]]
text = "eternal Father, and"
verses = "Romans 8:3; Ephesians 1:6; John 1:12; 1 John 1:3"

[[sections]]
text = "we are but Sons adopted of the Father by Grace for his sake."
verses = ""
