id = "31"
question = "But why are you called a Christian?"

[[sections]]
text = "Because through Faith I am a member of"
verses = "Acts 11:26; 1 Corinthians 6:15"

[[sections]]
text = "Jesus Christ,"
verses = "1 John 2:27; Isaiah 59:2; 1 John 2:28"

[[sections]]
text = "and partaker of his anointing, that both I"
verses = "Matthew 10:33"

[[sections]]
text = "may confess his name, and present my self unto him"
verses = "Romans 12:1; Apocalypse 5:8; 1 Peter 2:5; 2 Timothy 2:12; Romans 6:12,13; Apocalypse 1:6; 1 Timothy 1:18,19"

[[sections]]
text = "a lively Sacrifice of thankfulness, and also may in this life fight against Sin and Satan with free and good conscience, and"
verses = ""

[[sections]]
text = "afterwards enjoy an everlasting Kingdom with Christ."
verses = ""
