id = "32"
question = "Why do you call him our Lord?"

[[sections]]
text = "Because he redeeming and ransoming both our Body and Soul from Sin, not with Gold nor Silver, but with his precious Blood, and delivering us from all the Power of the Devil, has set"
verses = "1 Peter 1:18; 1 Corinthians 6:20; Ephesians 1:7; 1 Timothy 2:5,6; Romans 14:9"

[[sections]]
text = "us free to serve him."
verses = ""
