id = "33"
question = "What do you believe when you say, He was conceived by the Holy Ghost, and born of the Virgin Mary?"

[[sections]]
text = "That the Son of God, who"
verses = "Romans 9:5; Isaiah 7:14; Isaiah 9:6; John 5:20; John 20:28"

[[sections]]
text = "is and continues true and"
verses = "John 1:14; Galatians 4:4"

[[sections]]
text = "everlasting"
verses = "Romans 1:3"

[[sections]]
text = "God, took the"
verses = "Philippians 2:7; Hebrews 4:15; Hebrews 7:26"

[[sections]]
text = "very Nature of man, of the flesh and blood of the Virgin Mary, through the working of the"
verses = ""

[[sections]]
text = "Holy-Ghost, that he might also be the true Seed of"
verses = ""

[[sections]]
text = "David, like unto his Brethren in all things"
verses = ""

[[sections]]
text = "Sin excepted."
verses = ""
