id = "34"
question = "What profit do you take by Christ's holy Conception and Nativity?"

[[sections]]
text = "That he is our Mediator, and does cover with his Innocency and perfect Holiness my Sins, in which I was conceived, that they may not come in the Sight of"
verses = "Hebrews 2:16,17"

[[sections]]
text = "God."
verses = "Psalm 32:1; 1 Corinthians 1:30; Romans 8:3,4; Galatians 4:4,5"
