id = "35"
question = "What do you believe when you say he suffered?"

[[sections]]
text = "That he all the time of his life which he lead in the Earth, but especially at the end"
verses = "1 Peter 2:4; 1 Peter 3:18; Isaiah 53:12"

[[sections]]
text = "thereof, sustained the wrath of God, both in body and soul, against the sin of mankind, that he might by his passion, as the"
verses = "1 John 2:2; 1 John 4:10"

[[sections]]
text = "only propitiatory sacrifice, deliver our body and soul from everlasting damnation, and purchase us the favour of God, righteousness, and everlasting life."
verses = ""
