id = "37"
question = "For what cause should he suffer under Pilate, as being his Judge?"

[[sections]]
text = "That he being innocent"
verses = "Luke 23:14; John 19:4"

[[sections]]
text = "and condemned before a civil Judge"
verses = "Psalm 69:4; Isaiah 53:4,5; 2 Corinthians 5:21; Galatians 3:13"

[[sections]]
text = "might deliver us from the severe Judgment of God which remained for all men."
verses = ""
