id = "37"
question = "But is there any more in it, that he was fastened to the Cross, than if he had suffered any other kind of death?"

[[sections]]
text = "There is more: for by this I am assured that he took upon himself the curse which did lie on me; for the death of the Cross"
verses = "Deuteronomy 21:23; Galatians 3:13"

[[sections]]
text = "was accursed of God."
verses = ""
