id = "38"
question = "Why was it necessary for Christ to humble himself unto death?"

[[sections]]
text = "Because the Justice and Truth of God could by"
verses = "Genesis 2:17"

[[sections]]
text = "no other means be satisfied for our sins, but by the very death of the"
verses = "Hebrews 2:9,14,15; Philippians 2:8"

[[sections]]
text = "Son of God."
verses = ""
