id = "40"
question = "To what end was he buried also?"

[[sections]]
text = "That thereby he might manifest that he"
verses = "Acts 13:29; Matthew 27:60; Luke 23:53; John 19:38"

[[sections]]
text = "was dead indeed."
verses = ""
