id = "41"
question = "What other benefit do we receive by the Death of Christ?"

[[sections]]
text = "That by the virtue of his Death our old man is crucified, slain, and"
verses = "Romans 6:6"

[[sections]]
text = "buried together with him, (figured out in holy Baptism) that from now on evil lusts and desires may"
verses = "Romans 6:12"

[[sections]]
text = "not reign in us, but we"
verses = ""

[[sections]]
text = "may offer ourselves unto him a Sacrifice of thanksgiving."
verses = "Romans 12:1"
