id = "41"
question = "But since that Christ died for us, why must we also die?"

[[sections]]
text = "Our death is not a satisfaction for our Sins, but the abolishing of Sin, and our passage"
verses = "John 5:24; 1 Philippians 1:23; Romans 7:24"

[[sections]]
text = "into everlasting Life."
verses = ""
