id = "43"
question = "Why is there added, he descended into Hell?"

[[sections]]
text = "That in my greatest pains and most grievous temptations I may support my self with this comfort, that my Lord Jesus Christ"
verses = "Isaiah 53:10; Matthew 27:46"

[[sections]]
text = "has delivered me (by the unspeakable distresses, torments and terrors of his Soul, into which he was plunged both before, and then especially when he hanged on the Cross) from the straits and torments of Hell."
verses = ""
