id = "44"
question = "What does the Resurrection of Christ profit us?"

[[sections]]
text = "First, by his Resurrection he vanquished death, that he"
verses = "1 Corinthians 15:6; 1 Corinthians 15:4,5,6; Romans 4:25; 1 Peter 1:3"

[[sections]]
text = "might make us partakers of that Righteousness which he had gotten us by his death. Again, we are now"
verses = ""

[[sections]]
text = "also stirred up by his Power to a new Life. Lastly, the Resurrection of our head, Christ, is a"
verses = "Romans 6:4; Colossians 3:1; Ephesians 2:5"

[[sections]]
text = "Pledge unto us of our glorious Resurrection."
verses = "1 Corinthians 15:12; Romans 8:11"
