id = "45"
question = "How understand you that he ascended into Heaven?"

[[sections]]
text = "That Christ, his Disciples looking on, was"
verses = "Acts 1:9; Mark 16:19; Luke 24:51"

[[sections]]
text = "taken up from the Earth into Heaven, and yet"
verses = ""

[[sections]]
text = "still is there for our sakes, and will be until he come again to judge the quick and"
verses = "Hebrews 4:14; Hebrews 7:25; Hebrews 9:11; Romans 8:34; Ephesians 4:10; Colossians 3:1"

[[sections]]
text = "the dead."
verses = "Acts 1:11; Matthew 24:30"
