id = "46"
question = "Are not by this means the two natures in Christ pulled asunder, if his Humanity be not wherever his Divinity is?"

[[sections]]
text = "No; for since his Divinity is incomprehensible, and"
verses = "Acts 7:38,44; Acts 17:27; Jeremiah 23:24"

[[sections]]
text = "every where present, it follows necessarily that it is beyond the bounds of his human Nature which he took unto him, and yet is nevertheless in it,"
verses = ""

[[sections]]
text = "and abides personally united to it."
verses = "Colossians 2:9; Matthew 28:6"
