id = "46"
question = "Is not Christ with us then until the end of the World, as he has promised?"

[[sections]]
text = "Christ is true God, and true Man, and so according to his Manhood is not now on Earth, but according to his Godhead, his Majesty, his Grace, and"
verses = "Matthew 28:20; Matthew 26:11; John 16:18; John 17:11; Acts 3:21"

[[sections]]
text = "Spirit is at no time from us."
verses = "John 14:17; John 16:13; Ephesians 4:8"
