id = "47"
question = "Are not by this means the two natures in Christ pulled asunder, if his Humanity be not wheresoever his Divinity is?"

[[sections]]
text = "No; for seeing his Divinity is incomprehensible, and"
verses = "Acts 7:38,44; Acts 17:27; Jeremiah 23:24"

[[sections]]
text = "every where present, it follows necessarily that the same is without the bounds of his humane Nature which he took unto him, and yet is nevertheless in it,"
verses = ""

[[sections]]
text = "and abides personally united to it."
verses = "Colossians 2:9; Matthew 28:6"
