id = "48"
question = "What Fruit does the Ascension of Christ into Heaven bring unto us?"

[[sections]]
text = "First that"
verses = "1 John 2:1,2; Romans 8:34"

[[sections]]
text = "he makes Intercession to his Father in Heaven for us; next that we have our Flesh in Heaven, that we may be confirmed thereby, as by a sure Pledge, that it shall come to pass that he who is our Head"
verses = "John 14:2; John 20:17; Ephesians 2:6"

[[sections]]
text = "will lift us up, his Members, unto him: thirdly, that"
verses = "John 14:16; John 16:7; 2 Corinthians 5:5"

[[sections]]
text = "he sends us his Spirit instead of a Pledge between him and us, by whose forcible working we seek after not earthly but heavenly things, where he himself"
verses = "Colossians 3:1; Philippians 3:20"

[[sections]]
text = "is sitting at the Right-Hand of God."
verses = ""
