id = "49"
question = "Why is it further said, he sits at the Right-Hand of God?"

[[sections]]
text = "Because Christ therefore is ascended into Heaven, to"
verses = "Ephesians 1:20; Ephesians 5:23; Colossians 1:18"

[[sections]]
text = "show there that he is the Head of his Church, by whom the Father"
verses = ""

[[sections]]
text = "governs all things."
verses = "Matthew 28:18; John 5:22"
