id = "49"
question = "What profit is this Glory of our Head Christ unto us?"

[[sections]]
text = "First, that through his Holy Spirit"
verses = "Ephesians 4:16"

[[sections]]
text = "he pours upon us his Members heavenly Graces, then that he shields and"
verses = ""

[[sections]]
text = "defends us by his Power against all our Enemies."
verses = "Psalm 2:9; Psalm 110:2; John 10:28; Ephesians 4:8"
