id = "50"
question = "What Comfort have you by the coming of Christ again to judge the quick and the dead?"

[[sections]]
text = "That in all my Miseries and Persecutions, I look with my"
verses = "Luke 21:28; Romans 8:23; Philippians 3:20; Titus 2:13"

[[sections]]
text = "Head lifted up, for the very same who before yielded himself unto the Judgment of God for"
verses = "2 Thessalonians 1:6,7; 1 Thessalonians 4:16; Matthew 25:41"

[[sections]]
text = "me, and took away all Malediction from me, to come Judge from Heaven to throw all his and my Enemies into everlasting Pains; but to"
verses = ""

[[sections]]
text = "translate me with all his chosen unto himself, into Celestial Joys, and everlasting Glory."
verses = "Matthew 25:34"
