id = "52"
question = "What do you believe concerning the Holy Ghost?"

[[sections]]
text = "First, that He is true and Coeternal God, with the"
verses = "Genesis 1:2; Isaiah 48:16; 1 Corinthians 3:16; 1 Corinthians 6:19; Acts 5:3,4"

[[sections]]
text = "eternal Father, and the Son; secondly, that he is"
verses = "Matthew 28:19; 2 Corinthians 1:2"

[[sections]]
text = "also given unto me, to make"
verses = "Galatians 3:14; 1 Peter 1:2; 1 Corinthians 6:17"

[[sections]]
text = "me, through a true Faith, Partaker of Christ and all his Benefits, to"
verses = "Acts 9:31"

[[sections]]
text = "comfort me, and to"
verses = ""

[[sections]]
text = "abide with me for ever."
verses = "John 14:16; 1 Peter 4:14"
