id = "53"
question = "What do you believe concerning the Holy and Catholic Church of Christ?"

[[sections]]
text = "I believe that the Son"
verses = "Isaiah 59:21; Ephesians 5:26"

[[sections]]
text = "of God does from"
verses = "Acts 2:4,41; Ephesians 4:3,4,5,6"

[[sections]]
text = "the beginning of the"
verses = "Matthew 16:18"

[[sections]]
text = "World to the End thereof, gather,"
verses = "1 John 3:21; 2 Corinthians 13:5"

[[sections]]
text = "defend, and preserve unto himself by his Spirit"
verses = ""

[[sections]]
text = "and Word, out of"
verses = ""

[[sections]]
text = "whole Mankind, a"
verses = ""

[[sections]]
text = "Company chosen to everlasting Life, and agreeing in true Faith; and that I am a lively Member of that Company, and so shall"
verses = ""

[[sections]]
text = "remain for ever."
verses = ""
