id = "54"
question = "What mean those words, The Communion of Saints?"

[[sections]]
text = "First, that all and every one who believes, are in"
verses = "1 John 1:3; Romans 8:32; 1 Corinthians 1:2; 1 Corinthians 13:21; 1 Corinthians 6:17"

[[sections]]
text = "common Partakers of Christ and all his Graces, as being his Members; and then that every one ought"
verses = ""

[[sections]]
text = "readily and cheerfully to bestow the Gifts and Graces which they have received to the common Commodity and Safety of all."
verses = "1 Corinthians 12:21; Philippians 2:4,5,6"
