id = "54"
question = "What do you believe concerning Remission of Sins?"

[[sections]]
text = "That God, for the Satisfaction made by Christ,"
verses = "1 John 2:2; 2 Corinthians 5:19,21"

[[sections]]
text = "has put out all the"
verses = "Jeremiah 31:34; Psalm 103:3,4; Psalm 10:11; Romans 7:24,25; Romans 8:1,2,3"

[[sections]]
text = "Remembrance of my Sins, and also of that Corruption within me with which I must fight all my lifetime, and does freely endow me with the Righteousness of Christ, that I come not at any"
verses = "John 3:18"

[[sections]]
text = "time into Judgment."
verses = ""
