id = "55"
question = "What Comfort have you by the Resurrection of the Flesh?"

[[sections]]
text = "That not only my Soul, after it shall depart out of my Body, shall"
verses = "Luke 23:43; Philippians 1:23"

[[sections]]
text = "immediately be taken up to Christ, but that this my Flesh also, being raised up by the Power of Christ, shall be again united to my Soul, and"
verses = ""

[[sections]]
text = "shall be made like to the glorious Body of Christ."
verses = "1 Corinthians 15:53; Job 19:25,26; 1 John 3:2; Philippians 3:21"
