id = "56"
question = "What Comfort do you take of the Article of everlasting Life?"

[[sections]]
text = "That since"
verses = "2 Corinthians 5:1,2,3"

[[sections]]
text = "as I feel already in my Heart the beginning of everlasting Life,"
verses = ""

[[sections]]
text = "it shall at length come to pass that after this Life I shall enjoy full and perfect Bliss, in which I may magnify God for ever, which Blessedness truly neither Eye has seen, nor Ear heard, neither has any Man in thought conceived it."
verses = "1 Corinthians 2:9; John 17:3"
