id = "58"
question = "But when you believe all these things, what profit redounds thence unto you?"

[[sections]]
text = "That I am righteous in Christ before God, and an Heir"
verses = "Romans 1:17; John 3:36; Romans 3:4; Romans 22:24,25,28; Romans 5:1; Galatians 2:16; Ephesians 2:8,9"

[[sections]]
text = "of eternal Life."
verses = ""
