id = "59"
question = "How are you righteous before God?"

[[sections]]
text = "Only by Faith in Christ Jesus. So that although my Conscience accuse me that I have grievously trespassed against all the Commandments of God, and have not"
verses = "Romans 3:9"

[[sections]]
text = "kept one of them, and further am as yet"
verses = "Romans 7:23"

[[sections]]
text = "prone to all Evil, yet notwithstanding if"
verses = "Romans 3:22; John 3:18"

[[sections]]
text = "I embrace these Benefits of Christ with a true Confidence and Persuasion of mind, the full and"
verses = "Titus 3:5; Ephesians 2:8,9"

[[sections]]
text = "perfect Satisfaction, Righteousness and Holiness of Christ, without any"
verses = "1 John 2:2"

[[sections]]
text = "Merit of Mine, of the"
verses = "Romans 3:24; Deuteronomy 9:5,6; Ezekiel 36:22"

[[sections]]
text = "mere Mercy"
verses = "1 John 2:1"

[[sections]]
text = "of God is"
verses = "Romans 4:4,5; 2 Corinthians 5:19"

[[sections]]
text = "imputed and given unto me, and that so, as if neither I had committed any Sin, neither any Corruption did stick unto me; yea as if I my"
verses = ""

[[sections]]
text = "self had perfectly accomplished that Obedience which Christ accomplished for me."
verses = "1 Corinthians 5:21"
