id = "60"
question = "Why cannot our good Works be Righteousness, or some part of Righteousness before God?"

[[sections]]
text = "Because that Righteousness which must stand fast before the Judgment of God, must be in all Points perfect"
verses = "Galatians 3:10; Deuteronomy 27:26"

[[sections]]
text = "and agreeable to the Law of God. Now our Works, even the best of them, are imperfect in this Life, and"
verses = ""

[[sections]]
text = "defiled with Sin."
verses = "Isaiah 64:6"
