id = "60"
question = "Why do you affirm that you are made Righteous by Faith only?"

[[sections]]
text = "Not for that I please God through the Worthiness of mere Faith, but because only the Satisfaction, Righteousness and Holiness of Christ is my Righteousness"
verses = ""

[[sections]]
text = "before God, and"
verses = "1 Corinthians 1:30"

[[sections]]
text = "I cannot take hold of it, or apply it unto myself any other way than by Faith."
verses = "1 Corinthians 2:2; 1 John 5:10"
