id = "61"
question = "How is it that our good Works merit nothing, since God promises that he will give a Reward for them both in this Life, and in the Life to come?"

[[sections]]
text = "That Reward is not given of merit,"
verses = ""

[[sections]]
text = "but of Grace."
verses = "Luke 17:10"
