id = "63"
question = "But does not this Doctrine make Men careless and profane?"

[[sections]]
text = "No, For neither can it be but they who are incorporated into Christ through Faith, should bring forth the"
verses = "Matthew 7:18; John 15:5"

[[sections]]
text = "Fruits of Thankfulness."
verses = ""
