id = "64"
question = "Seeing then that only Faith makes us Partakers of Christ and his Benefits, whence does it proceed?"

[[sections]]
text = "From the Holy Ghost"
verses = "Ephesians 2:8; Ephesians 6:23; John 3:5; Philippians 1:29"

[[sections]]
text = "who kindles it in our Hearts by the preaching of the Gospel, and other Ordinances, and"
verses = ""

[[sections]]
text = "confirms it by the use of the Sacraments."
verses = "Matthew 28:19,20; 1 Peter 1:22,23"
