id = "65"
question = "What are the Sacraments?"

[[sections]]
text = "They are sacred Signs, and Seals, set before our Eyes, and ordained of God for this cause, that he may declare and seal by them the Promise of his Gospel unto us, to wit, that he gives freely Remission of Sins, and"
verses = ""

[[sections]]
text = "Life everlasting, not only to his all in general, but to every one in particular that believes, for that only Sacrifice of Christ which he accomplished upon the Cross."
verses = "Genesis 17:11; Romans 4:11; Deuteronomy 30:6; Leviticus 6:25; Hebrews 9:8,9; Ezekiel 20:12; Isaiah 6:6,7; Isaiah 54:9,10"
