id = "66"
question = "Do not then both the Word and Sacraments tend to that End, as to lead our Faith unto the Sacrifice of Christ finished on the Cross as to the only ground of our Salvation?"

[[sections]]
text = "It is even so; for the Holy Ghost teaches us by the Gospel, and assures us by the Sacraments, that the Salvation of all of us stands in the only Sacrifice"
verses = ""

[[sections]]
text = "of Christ offered for us upon the Cross."
verses = "Romans 6:3; Galatians 3:17"
