id = "68"
question = "What is Baptism?"

[[sections]]
text = "Immersion or dipping of the Person in Water in the Name of the Father, Son, and Holy Ghost, by such who are duly qualified by Christ."
verses = "Matthew 3:16; John 3:23; Acts 8:38,39; Romans 6:4"
