id = "68"
question = "Who are the proper Subjects of this Ordinance?"

[[sections]]
text = "Those who do actually profess Repentance towards God, Faith in, and Obedience to our Lord Jesus Christ."
verses = "Acts 2:38; Acts 8:36,37"
