id = "70"
question = "Does the Scripture any where expressly forbid the Baptizing of Infants?"

[[sections]]
text = "It is sufficient that the Divine Oracle commands the baptizing of Believers, unless we will make ourselves wiser than what is written. Nadab and Abihu were not forbidden to offer strange Fire, yet for so doing they incurred God's Wrath, because they were commanded to take Fire from the Altar."
verses = "Matthew 28:18,19; Mark 16:16; Leviticus 9:24; Leviticus 10:16"
