id = "72"
question = "May not the Infant Seed of Believers under the Gospel be baptized as well as the Infant Seed of Abraham under the Law was circumcised?"

[[sections]]
text = "No; For Abraham had a Command then from God to circumcise his Infant Seed; but Believers have no Command to baptize their Infants Seed under the Gospel."
verses = "Genesis 17:9,10,11,12"
