id = "72"
question = "Are the Infants of Believers in the Covenant of Grace so as to warrant their Baptism, as Abraham's Infant Seed was circumcised under the Law?"

[[sections]]
text = "By the Infants of Believers being in the Covenant of Grace, it must either be meant absolutely or conditionally; and neither warrants their Baptism."
verses = ""
