id = "73"
question = "Seeing the Infants of Believers are in the Covenant of Grace with their Parents, as some say, why may not they be baptized under the Gospel, as well as Abrahams Infant Seed was circumcised under the Law?"

[[sections]]
text = "By the Infants of Believers being in the Covenant of Grace, it must either be meant of the Covenant of Grace absolutely considered, and if so, then there is no total and final Apostasy of any Infant seed of Believers from the Covenant, but all must be saved then."
verses = "Jeremiah 32:38,39,40; John 10:28"

[[sections]]
text = "Or, 2. They must mean conditionally, on consideration that when they come to years of maturity, they by true Faith, Love, and Holiness of life, taking hold of God's Covenant of Grace, shall have the Privileges of it. This being their sense, I then demand what real spiritual privilege the Infant-Seed of Believers, as such, have more than the Infant Seed of Unbelievers, if they live also to years of maturity, and by true Faith and Love take hold of God's Covenant"
verses = ""

[[sections]]
text = "? I further demand, whether the Seal of the Covenant do not under those considerations belong as much to the Children of Unbelievers as to the Children of Believers? yea, and more too, under consideration the Infant Seed of the Unbeliever should take hold of God's Covenant, and the Believers Infant-Seed do not"
verses = "Isaiah 56:3,4,5,6,7,8; Acts 10:34,35; John 3:16"

[[sections]]
text = "; as often this is seen to the sorrow of many Godly Parents. 3. Suppose all the Infant Seed of Believers absolutely in the Covenant of Grace; yet Believers under the Gospel ought no more to Baptize their Infant-Seed, than Lot to circumcise himself or his Infant-Seed, if he had had Males as well as Females, albeit nearly related to Abraham, yea, a Believer, and in the Covenant of Grace too: forasmuch as Circumcision was limited to Abraham and to his Family. Also by the same rule we may bring Infants to the Lord's Table, forasmuch as the same qualifications are"
verses = ""

[[sections]]
text = "required to the due performance of Baptism, as there is to the Lord's Supper."
verses = "Acts 2:41,42"

[[sections]]
text = "4. We must know the Covenant made with Abraham had two parts: first, a spiritual, which consisted in God's promising to be a God to"
verses = ""

[[sections]]
text = "Abraham, and"
verses = ""

[[sections]]
text = "all his Spiritual-Seed in a peculiar manner, whether they were circumcised or uncircumcised, which believed as Abraham the Father of the Faithful did. And this was signified in God's accepting such as his People which were not of"
verses = ""

[[sections]]
text = "Abrahams Seed, but bought with his Money, and this Promise was sealed to Abraham by Circumcision, that through Jesus Christ (whom Isaac typified our) the Gentiles, the Uncircumcision which believed, should have their Faith counted for Righteousness, as Abrahams was before he was circumcised."
verses = "Genesis 17:19,21; Genesis 21:10; Galatians 4:30; Acts 2:39; Romans 9:7,8; Galatians 3:16; Romans 4:9,10,11,12,13,14"

[[sections]]
text = "2. This Promise consisted of temporal good: so God promised Abrahams Seed should injoy the"
verses = ""

[[sections]]
text = "Land of Canaan, and have plenty of outward blessings, so sealed this Promise by Circumcision. It was also a distinguishing character of the Jews being God's People from all the Nations of the Gentiles, which as yet were not the Seed of Abraham: but when the Gentiles came to believe, and by Faith became the People of God as well as the Jews, then"
verses = ""

[[sections]]
text = "Circumcision, that distinguishing Mark, ceased; and the character of being the Children of God now, is Faith in Christ, and Circumcision of the Heart. So that whatever pretence there may be for the Infants of Believers to be Baptized first, as their being the Seed of Believers; or 2dly, their being in the Covenant; or 3dly, that the Infant-Seed of Abraham a Believer, was circumcised; all this you see avails nothing: for Circumcision was limited to such a Family, the Family of Abraham, all others, though Believers, were excluded; also limited to such a day, the eighth day, and what ever pretence might be made, it was not to be done before nor after; limited also to such a Sex, the Male, not the Female; which if Baptism came in the room of Circumcision, and is the Seal of the Covenant under the Gospel, as Circumcision was under the Law, none but the Males must be Baptized, because none but the Males were Circumcised; but as under the Law respecting Circumcision, so now under the Gospel respecting Baptism, it depends purely upon the will of the Law-giver, at what season, upon what Persons and terms Baptism is to be administered; unto which Prophet we shall all do well to hearken, Acts 3:22."
verses = "Genesis 15:18; Genesis 17:6,9,10,11; Genesis 12:6,7; Genesis 13:15,16,17; Genesis 15:16; John 1:12; Romans 2:28,29; Philippians 3:3; Galatians 3:26,27,28"
