id = "73"
question = "Are the Infants of Believers in the Covenant absolutely?"

[[sections]]
text = "If so, then there is no total and final Apostasy of any Infant Seed of Believers from the Covenant, but all must be saved."
verses = "Jeremiah 32:38,39,40; John 10:28"
