id = "74"
question = "How are you admonished and assured in Baptism, that you are Partaker of the only Sacrifice of Christ?"

[[sections]]
text = "Because Christ commanded the outward washing of Water, adjoining"
verses = ""

[[sections]]
text = "this Promise thereunto, that I am no less assuredly washed by his Blood and Spirit from the uncleanness of my Soul, that is, from all my Sins, than I am"
verses = ""

[[sections]]
text = "washed outwardly with Water, whereby all the Filthiness of the Body uses to be purged."
verses = "Matthew 28:19; Acts 2:38; Mark 16:16; Matthew 3:11; Romans 6:3; Matthew 1:4; Luke 3:3"
