id = "74"
question = "Are the Infants of Believers in the Covenant conditionally?"

[[sections]]
text = "If conditionally, on consideration that when they come to years of maturity, they by true Faith, Love, and Holiness of life, taking hold of God's Covenant of Grace, shall have the Privileges of it; then what real spiritual privilege have the Infant-Seed of Believers, as such, more than the Infant Seed of Unbelievers, if they live also to years of maturity, and by true Faith and Love take hold of God's Covenant?"
verses = ""

[[sections]]
text = "I further demand, whether the Seal of the Covenant do not under those considerations belong as much to the Children of Unbelievers as to the Children of Believers? Indeed, and more too, under consideration the Infant Seed of the Unbeliever should take hold of God's Covenant, and the Believers Infant-Seed do not; as often this is seen to the sorrow of many Godly Parents."
verses = "Isaiah 56:3,4,5,6,7,8; Acts 10:34,35; John 3:16"

[[sections]]
text = "Suppose all the Infant Seed of Believers absolutely in the Covenant of Grace; yet Believers under the Gospel ought no more to Baptize their Infant-Seed, than Lot to circumcise himself or his Infant-Seed, if he had had Males as well as Females, even though he was closely related to Abraham, indeed a Believer, and in the Covenant of Grace too: since Circumcision was limited to Abraham and to his Family."
verses = ""
