id = "75"
question = "If Infants of Believers are in the Covenant either conditionally or absolutely, should they not gain access to the Lord's Supper as well?"

[[sections]]
text = "Indeed, by the same rule we must also bring Infants to the Lord's Table, since the same qualifications are"
verses = ""

[[sections]]
text = "required to the due performance of Baptism, as there is to the Lord's Supper. Yet those who baptize Infants will not bring them to the Lord's Table; and if there is no warrant for the one, neither is there warrant for the other."
verses = "Acts 2:41,42"
