id = "76"
question = "Where does Christ promise us that he will as certainly wash us with his Blood and Spirit, as we are washed with the Water of Baptism?"

[[sections]]
text = "In the Institution of Baptism, the words whereof are these,"
verses = ""

[[sections]]
text = "Go, teach all Nations, baptizing them in the Name of the Father, the Son, and the Holy Ghost:"
verses = ""

[[sections]]
text = "he that shall believe, and be baptized, shall be saved; but he that will not believe, shall be damned. This Promise is repeated again when as the Scripture calls Baptism the"
verses = ""

[[sections]]
text = "washing of the New-birth, and"
verses = ""

[[sections]]
text = "forgiveness of Sins."
verses = "Matthew 28:19; Mark 16:16; Titus 3:5; Acts 22:16"
