id = "77"
question = "Is then the outward Baptism of Water the washing away of Sins?"

[[sections]]
text = "It is not; for the"
verses = ""

[[sections]]
text = "Blood of Christ alone cleanses us from"
verses = ""

[[sections]]
text = "all Sin."
verses = "1 Peter 3:21; Ephesians 5:25,26; 1 John 1:7; 1 Corinthians 6:11"
