id = "77"
question = "What was the temporal part of the Covenant?"

[[sections]]
text = "God promised Abraham's Seed should enjoy the Land of Canaan, and have plenty of outward blessings, so sealed this Promise by Circumcision. It was also a distinguishing character of the Jews being God's People from all the Nations of the Gentiles, which as yet were not the Seed of Abraham: but when the Gentiles came to believe, and by Faith became the People of God as well as the Jews, then Circumcision, that distinguishing Mark, ceased; and the character of being the Children of God now, is Faith in Christ, and Circumcision of the Heart."
verses = "Genesis 15:18; Genesis 17:6,9,10,11; Genesis 12:6,7; Genesis 13:15,16,17; Genesis 15:16; John 1:12; Romans 2:28,29; Philippians 3:3"
