id = "78"
question = "Why then does the Holy Ghost call Baptism the washing of the New-birth, and forgiveness of Sins?"

[[sections]]
text = "God speaks to not without great cause, to wit, not only to teach us that as the filth of our Body is purged by Water, so our Sins also are"
verses = ""

[[sections]]
text = "purged by the Blood and Spirit of Christ, but much more to assure us by this divine Token and Pledge, that we are as verily washed from our Sins with the inward washing, as we are"
verses = ""

[[sections]]
text = "washed by the outward and visible Water."
verses = "Apocalypse 1:5; Apocalypse 7:14; 1 Corinthians 6:11; Mark 16:16; Galatians 3:17"
