id = "78"
question = "What was the spiritual part of the Covenant?"

[[sections]]
text = "God promised to be a God to Abraham, and all his Spiritual-Seed in a peculiar manner, whether they were circumcised or uncircumcised, which believed as Abraham the Father of the Faithful did. And this was signified in God's accepting such as his People which were not of Abraham's Seed, but bought with his Money, and this Promise was sealed to Abraham by Circumcision, that through Jesus Christ (whom Isaac typified) the Gentiles, the Uncircumcision which believed, should have their Faith counted for Righteousness, as Abraham's was before he was circumcised."
verses = "Genesis 17:19,21; Genesis 21:10; Galatians 4:30; Acts 2:39; Romans 9:7,8; Galatians 3:16; Romans 4:9,10,11,12,13,14"
