id = "79"
question = "What Principle of Christ's Doctrine in the holy Scripture follows Baptism in order?"

[[sections]]
text = "Laying on of Hands, as in Hebrews 6:1,2."
verses = ""

[[sections]]
text = "What is the form and end of this Ordinance? Christ's Ministers laying their hands solemnly upon the Head of the Baptized, with Prayer to Almighty God for an increase of the Graces"
verses = ""

[[sections]]
text = "and Gifts of the"
verses = ""

[[sections]]
text = "Holy Ghost, to inable us to hold fast the Faith which we now visibly own, having entred into the Church by Holy Baptism, and also be helped thereby to maintain a constant War against the"
verses = ""

[[sections]]
text = "World, Flesh, and the Devil."
verses = "2 Timothy 1:6; Acts 2:38,39; John 14:16,17,18,26; John 16:7; Ephesians 1:13,14"
