id = "80"
question = "What is it to be washed with the Blood and Spirit of Christ?"

[[sections]]
text = "It is to receive of God Forgiveness of Sins freely, for the Blood of Christ which"
verses = ""

[[sections]]
text = "he shed for us in his Sacrifice upon the Cross; and also to be renewed by the Holy Ghost, and through his sanctifying of us to become Members of Christ, that we may more and more die to Sin, and"
verses = ""

[[sections]]
text = "live holily and without blame."
verses = "Hebrews 12:24; 1 Peter 1:2; Apocalypse 1:5; Zechariah 13:1; Ezekiel 36:25; John 1:33; John 3:5; 1 Corinthians 5:11; 1 Corinthians 12:13; Romans 6:4; Colossians 2:12"
