id = "82"
question = "How are you in the Lord's Supper admonished and warranted that you are Partaker of that only Sacrifice of Christ offered on the Cross, and of all his Benefits?"

[[sections]]
text = "Because Christ has commanded me and all the Faithful to eat of this Bread broken, and to drink of this Cup, distributed in Remembrance of him, with this Promise"
verses = ""

[[sections]]
text = "adjoined, first, that his Body was as certainly broken and offered for me upon the Cross, and his Blood shed for me, as I behold with my Eyes the Bread of the Lord broken unto me, and the Cup communicated unto me; and further, that my Soul is no less assuredly fed to everlasting life with his Body, which was crucified for me, and his Blood which was shed for me, than I receive and taste by the Mouth of my Body, the Bread and Wine, the Signs of the Body and Blood of our Lord, received at the Hand of the Minister."
verses = "Matthew 26:27,28; Mark 14:22,23,24; Luke 22:16,20; 1 Corinthians 10:16,17; 1 Corinthians 11:23,24,25; 1 Corinthians 12:13"
