id = "84"
question = "Where has Christ promised that he will as certainly give his Body and Blood so to be eaten and drunken, as they eat this Bread broken, and drink this Cup?"

[[sections]]
text = "In the Institution of the Supper, the Words whereof are these."
verses = ""

[[sections]]
text = "Our Lord Jesus Christ in the Night that he was betrayed, took Bread, and when he had given thanks, he brake it, and said, Take, eat, this is my Body which is broken for you: this do in Remembrance of me. Likewise also he took the Cup, when he had supped, and"
verses = ""

[[sections]]
text = "said, This Cup, is the new Testament in my"
verses = ""

[[sections]]
text = "Blood; this do as often as ye shall drink it in Remembrance of me: for as often as ye shall eat this Bread, and drink this Cup, ye shew the Lords Death till he come."
verses = "1 Corinthians 11:23; Matthew 26:26; Mark 14:22; Luke 22:19; Exodus 24:8; Hebrews 9:20; Exodus 13:9"

[[sections]]
text = "This Promise, is repeated by St. Paul where he saith, The Cup of blessing which we bless, is it not the Communion of the Blood of Christ? the Bread which we break, is it not the Communion of the Body of Christ? for we that are many, are one Bread, and one Body, because we are all Partakers of one Bread."
verses = "1 Corinthians 10:16,17"
