id = "85"
optional = true
section = "laying-on-of-hands"
question = "Is it the Duty of every Christian to be under this Practice?"

[[sections]]
text = "It is so: And appears plainly, if we do first consider the Practice of the Primitive Saints, we may read in Acts 8:12-19, of Men and Women that were baptized by Philip in Samaria, which when the Church at Jerusalem heard thereof, they sent down St. Peter and St. John (two Apostles) to them, who when they came thither, laid their Hands on them, and they received the Holy Ghost."
verses = ""
