id = "85"
question = "Are then the Bread and Wine made the very Body and Blood of Christ?"

[[sections]]
text = "No, verily; but as the Water of Baptism"
verses = ""

[[sections]]
text = "is not turned into the Blood of Christ, but is only a Sign and Pledge of those things that are sealed to us in Baptism; so neither is the Bread of the Lords Supper the very Body"
verses = ""

[[sections]]
text = "of Christ, although according to the manner of Sacraments, and"
verses = ""

[[sections]]
text = "that Form of Speaking of them which is usual unto the Holy Ghost, the Bread is called the Body of Christ."
verses = "1 Corinthians 10:16,17; Matthew 26:28; Mark 14:24; 1 Corinthians 10:16; 1 Corinthians 11:26; Genesis 17:10; Exodus 12:26,27,43,48; Exodus 13:9; Acts 7:8; Exodus 24:8; Leviticus 16:10; Isaiah 6:6,7; Titus 3:5; Acts 22:16; 1 Peter 3:21; 1 Corinthians 10:4"
