id = "86"
optional = true
section = "laying-on-of-hands"
question = "But we do not find the three thousand in Acts 2, nor many others which were baptized, under this Ordinance; is it then truly universal?"

[[sections]]
text = "So likewise in Acts 19:6,7, when Paul came to Ephesus he found certain Disciples there who were baptized, but had not heard whether there was any Holy Ghost; then the Apostle lays his Hands on them, and they received the Holy Ghost; and the number of them was about twelve; and Reason shows us from this place, and Acts 8, where St. Peter and St. John laid hands on Men and Women, that had here been two hundred and forty, he would have laid his Hands on them all."
verses = ""

[[sections]]
text = "As to the three thousand it is plain enough they had been taught it, and doubtless so practiced this Ordinance, if we consider the Apostle writing to the Jews, in Hebrews 5, tells them they had need be taught again the first Principles of the Oracles of God, of which Oracles, Laying on of Hands was one. And as for others which were baptized, where mention is not made of their being under this Ordinance, we may also say many hundreds were baptized which we have no mention of. Shall we conclude many of the Apostles were not baptized, because it is not particularly mentioned?"
verses = ""
