id = "87"
optional = true
section = "laying-on-of-hands"
question = "What then is the weight of this Ordinance in the Doctrine of Christ?"

[[sections]]
text = "We must conclude the primitive Saints were not short in this point, although it be not always specified; since it is called one of God's Oracles, as we all know the Moral Law was, which is perpetually binding, and universally obliging; also called a Principle of Christ's Doctrine, indeed one of the first Principles; and that is not all, but called a foundation Principle, this with the other five must be laid first in that foundation, on which the Superstructure of Christianity must be built."
verses = ""

[[sections]]
text = "And would it not have been very unbecoming the Jews when God gave them ten Commandments, for them to have excluded the fourth? is it not also as unbecoming for any to exclude the fourth Principle of Laying on of Hands, a practical Principle of the Doctrine of Christ, and so practiced by the Primitive Christians?"
verses = "Hebrews 5:1,2; Acts 7:38; Hebrews 1:2"
