id = "87"
question = "What Difference is there between the Supper of the Lord, and the Popish Mass?"

[[sections]]
text = "The Supper of the Lord testifies unto us, that we have perfect Forgiveness of all our Sins, for that only Sacrifice of Christ, which himself once"
verses = ""

[[sections]]
text = "fully wrought on the Cross; then also that we by Faith are grafted into"
verses = ""

[[sections]]
text = "Christ, who now according to his human Nature is only in Heaven at the Right-Hand of"
verses = ""

[[sections]]
text = "his Father, and there will be"
verses = ""

[[sections]]
text = "worshipped of us. But in the Mass it is denied that the quick and the dead have Remission of Sins, for the only Passion of Christ, except Christ also be daily offered for them by their Sacrificers: Further, also it is taught, that Christ is bodily under the Forms of Bread and Wine, and therefore is to be worshipped in them: and so the very Foundation of the Mass is nothing else but an utter denial of that only Sacrifice and Passion of Christ Jesus, and an accursed Idolatry."
verses = "Hebrews 7:27; Hebrews 9:12,26,28; Hebrews 10:10,12,14; John 19:30; Matthew 26:28; Luke 22:19,20; 1 Corinthians 6:17; 1 Corinthians 10:16; 1 Corinthians 11:13; Hebrews 1:3,6,8; John 4:21,22,23; John 20:17; Luke 24:51; Acts 7:55,56; Colossians 3:1; Philippians 3:20; 1 Thessalonians 1:9,10"
