id = "88"
optional = true
section = "laying-on-of-hands"
question = "Did not the extraordinary Gifts of the Spirit follow upon laying on of Hands in the Apostles' time?"

[[sections]]
text = "It did so: But not simply as the end of that Ordinance. For that Ordinance was appointed for the Ordinary Gifts of the Spirit to the World's end; though it is true, God honoured and crowned that Ordinance with Signs and Wonders in the primitive time, as he did others of his Appointment: as for instance, Acts 4, the Place was shaken, as the effect of the Churches Prayer; so Preaching was extraordinarily crowned when St. Peter converted three thousand at one Sermon; and in God's giving the Holy Ghost to the House of Cornelius while Peter was preaching, so that they spoke with Tongues, Acts 10."
verses = ""

[[sections]]
text = "Also God crowned the holy Ordinance of Baptism extraordinarily, when the Spirit came in the likeness of a Dove, and sat upon our Saviour Christ as he came out of the Water, Matthew 3, and a Voice heard from Heaven, saying, This is my beloved Son, in whom I am well pleased. Also the Eunuch's Baptism was wonderfully confirmed to him in God's taking away Philip as soon as he came up out of the Water, so that he went away rejoicing."
verses = ""
