id = "89"
question = "Are they also to be admitted to the Lords Supper who in Confession and Life declare themselves to be Infidels, profane, and ungodly?"

[[sections]]
text = "No; For by that means the Ordinance of God is profaned, and the Wrath of God is"
verses = ""

[[sections]]
text = "stirred up against the whole Assembly, wherefore the Church by the Commandment of Christ and his Apostles, inspired by the Holy Ghost, using the Keys of the Kingdom of Heaven, ought to drive them from this Supper till they shall repent and change their Manners."
verses = "1 Corinthians 11:20,34; Isaiah 1:11; Isaiah 66:3; Jeremiah 7:21; Psalm 50:16"
