id = "89"
optional = true
section = "laying-on-of-hands"
question = "Does the ceasing of these extraordinary signs mean that laying on of Hands also ceases?"

[[sections]]
text = "No; for as Prayer, Baptism, Preaching, does not cease, though it be not so miraculously owned as in the Primitive times; neither does laying on of Hands cease, from the same Parity of Reason, though it be not so crowned now, as in the Apostles' Days."
verses = ""

[[sections]]
text = "Moreover our Brethren generally do hold, that five of those Principles in Hebrews 6 are the Duty of every individual Member to believe and practice, namely, every Member (say they) ought to repent, believe, be baptized, believe the Resurrection of the dead, and eternal Judgment; and why this of laying on of Hands should be excluded from being the Practice of every Christian, being a practical Ordinance, the bare belief of it not being enough, it being among the universal Principles of Christ's Doctrine, I never yet did, nor cannot see any good Reason."
verses = ""
