id = "90"
question = "How ought this Ordinance of the Lords Supper to be closed?"

[[sections]]
text = "In singing Praises to God vocally and audibly for his great Benefits and Blessings to his Church in the shedding of the most precious Blood of his Son to take away their Sin; which Blessings are pointed out in this Sacrament. Also we find our Lord and his Disciples did close up this Ordinance in singing an Hymn or Psalm; and if Christ did sing, who was going to die, what cause have we to sing for whom he died, that we might not eternally die, but live a spiritual and eternal life with Father, Son, and Spirit, in unexpressible Glory."
verses = "Matthew 26:30"
