id = "91"
question = "What is it to eat the Body of Christ?"

[[sections]]
text = "It is not only to embrace, by an assured Confidence of Mind, the whole Passion and Death of Christ, and thereby to obtain Forgiveness of Sins, and everlasting Life, but also by the Holy Ghost, who dwells both in Christ and us, so more and more to"
verses = "John 6:35,40,47,48,50,51,53,54"

[[sections]]
text = "be united to his sacred Body, that though he be"
verses = "John 6:56"

[[sections]]
text = "in Heaven, and we on Earth, yet nevertheless we are Flesh of his Flesh, and Bone of his"
verses = "Acts 3:21; Acts 1:9; 1 Corinthians 11:26"

[[sections]]
text = "Bones: and as all the Members of the Body are quickened by one Soul; so are we also quickened and"
verses = "Ephesians 5:29,30,32; 1 Corinthians 6:15,17,19; 1 John 3:24; 1 John 4:13; John 14:23"

[[sections]]
text = "guided by one and the same Spirit."
verses = "John 6:56,57,58; John 15:1,2,3,4,5,6; Ephesians 4:15,16"
