id = "92"
question = "How is the Kingdom of Heaven opened and shut by preaching of the Gospel?"

[[sections]]
text = "When by the Commandment of Christ it is publickly declared to all and every one of the Faithful, that all their Sins are pardoned them of God for the Merit of Christ, so often as they imbrace by a lively Faith the Promise of the Gospel: but contrarily is denounced to all Infidels and Hypocrites, that so long the Wrath of God does lie on them, as they"
verses = ""

[[sections]]
text = "persist in their Wickedness, according to which Testimony of the Gospel God will judge them, as well in this life as in the life to come."
verses = "Job 20:21,22,23; Matthew 16:19; John 12:48"
