id = "94"
question = "Why then does Christ call Bread his Body, and the Cup his Blood, or the new Testament in his Blood; and St. Paul calls Bread and Wine the Communion of the Body and Blood of Christ?"

[[sections]]
text = "Christ, not without great Consideration, speaks so, namely, not only to teach us that as the Bread and Wine sustain the Life of the Body, so also his crucified Body, and Blood shed, are indeed the Meat and Drink of our Souls, by which they"
verses = ""

[[sections]]
text = "are nourished to eternal Life; but much more that by this visible Sign and Pledge, he may assure us that we are as truly Partakers of his Body and Blood, through the working of the"
verses = "John 6:51,55,56"

[[sections]]
text = "Holy Ghost, as we do perceive by the Mouth of our Body, these holy Signs in Remembrance of him; and further also, that his Sufferings and Obedience is so certainly ours, as though we ourselves had suffered Punishments for our Sins, and had satisfied God."
verses = "1 Corinthians 10:16,17"
