id = "94"
question = "Whereas we are delivered from all our Sins and Miseries without any Merit of ours, by the Mercy of God, only for Christ's sake; for what cause are we to do good Works?"

[[sections]]
text = "Because, after that Christ has redeemed us with his Blood, he renews us also by his Spirit to the Image of himself, that we receiving so great Benefits,"
verses = ""

[[sections]]
text = "should show our selves all our life time thankful to"
verses = "Romans 6:1,3; Romans 12:1,2; 1 Peter 2:5,9; 1 Corinthians 6:20"

[[sections]]
text = "God, and honour him; secondly that every one of us be"
verses = "1 Peter 2:12"

[[sections]]
text = "assured of his Faith by his Fruit; and lastly, that by our good Conversation we may"
verses = "2 Peter 1:10; Matthew 7:17,18; Galatians 5:22"

[[sections]]
text = "win others to Christ."
verses = "1 Peter 3:1,2; Matthew 5:16"
