id = "95"
question = "Cannot they then be Saved which be unthankful, and remain still careless in their Sins, and are not converted from their Wickedness to God?"

[[sections]]
text = "By no means; for as the Scripture bears Witness, neither unchaste Persons, nor Idolaters, nor Adulterers, nor Thieves, nor Covetous nor Drunkards, nor Slanderers, nor Robbers,"
verses = ""

[[sections]]
text = "shall enter in to the Kingdom of God."
verses = "1 Corinthians 6:9,10; Ephesians 5:5,6; 1 John 3:14,15"
