id = "96"
question = "Who are to come unto the Table of the Lord?"

[[sections]]
text = "They only, who are truly sorrowful they have offended God by their Sins, and yet trust that those Sins are pardoned them for Christ's sake; and what other Infirmities they have, that those are covered by his Passion and Death; who also desire more and more to go forward in Faith and Integrity of life: but Hypocrites, and them which do not truly repent, do eat"
verses = ""

[[sections]]
text = "and drink Damnation to themselves."
verses = "1 Corinthians 10:21; 1 Corinthians 11:28"
