id = "98"
question = "What is the quickening of the new Man?"

[[sections]]
text = "True Joy in God"
verses = ""

[[sections]]
text = "through Christ, and an earnest Desire to order your Life according to God's Will and to"
verses = "Romans 5:1; Romans 14:17; Isaiah 57:15"

[[sections]]
text = "do all good Works."
verses = "Romans 6:10,11; Galatians 2:20"
