id = "101"
question = "How are these Commandments divided?"

[[sections]]
text = "Into"
verses = ""

[[sections]]
text = "two Tables, whereof the former delivers in four Commandments, how we ought to behave our selves towards God: the latter delivers in six Commandments, what duties we"
verses = "Exodus 34:28; Deuteronomy 4:13; Deuteronomy 10:3,4"

[[sections]]
text = "owe unto our Neighbours."
verses = "Matthew 22:37,38,39"
