id = "101"
question = "How is the Kingdom of Heaven opened and shut by Ecclesiastical Discipline?"

[[sections]]
text = "When according to the Commandments of Christ, they who in Name are Christians, but in their Doctrine and life show"
verses = ""

[[sections]]
text = "themselves Aliens from Christ, after they have been some time admonished, will not depart from their Error, Heresies, or Wickedness, are made known unto the Church; and if neither then they obey the Churches Admonition, are by the same Church kept from the Sacrament, and shut out by Authority received from Christ, from the Congregation"
verses = "Romans 12:7,8,9; 1 Corinthians 12:28"

[[sections]]
text = "or Church, and by God himself out of the Kingdom of Heaven. And again, if they profess and declare an amendment of life, nothing to the contrary being to be proved upon strict scrutiny and search, are again to"
verses = "Matthew 18:15,16,17; 1 Corinthians 5:3,4,5; 2 Thessalonians 3:14,15"

[[sections]]
text = "be received in Love & Tenderness as Members of Christ and his Church."
verses = "2 Corinthians 2:6,7,10,11"
