id = "103"
question = "What learn we from this Preface?"

[[sections]]
text = "Three things: first he shows to whom the right of all Rule belongs, that is, to God himself, for I am (says he) JEHOVAH. Secondly, he says, he is the God of his People, that through the Promise of his Bountifulness he might allure them to obey him. Thirdly, he says, which brought you out of the Land of Egypt; as if he should say, I am he who have manifested my self unto you and bestowed all those Blessings upon you, therefore you are bound to show Thankfulness and Obedience unto me."
verses = "Exodus 20:2"
