id = "104"
question = "Do these things belong unto us?"

[[sections]]
text = "They do so, because they do figuratively comprehend and imply all the Deliverances of the Church; and further, also this was a Type of our wonderful Deliverance achieved by Christ."
verses = ""
