id = "104"
question = "Of what Parts consists the Conversion of Man unto God?"

[[sections]]
text = "It consists of the mortifying of the old Man, and a quickening of the new Man."
verses = "Romans 6:4,5,6; Ephesians 4:22,23,24; Colossians 3:5,8,9,10; 1 Corinthians 5:7; 2 Corinthians 7:11"
