id = "105"
question = "What is the mortifying of the old Man?"

[[sections]]
text = "To be truly and heartily sorry that you have offended God by your Sins, and daily more and more hate"
verses = ""

[[sections]]
text = "and eschew them."
verses = "Romans 8:13; Joel 2:13; Hosea 5:5"
