id = "106"
question = "What does God require in the first Commandment?"

[[sections]]
text = "That as dearly as I tender the Salvation of my own Soul, so earnestly should I shun and fly"
verses = ""

[[sections]]
text = "all Idolatry, Sorcery,"
verses = ""

[[sections]]
text = "Enchantments, Superstition, praying to Saints, or any"
verses = ""

[[sections]]
text = "other Creatures, and should"
verses = ""

[[sections]]
text = "rightly acknowledge the only and true God"
verses = ""

[[sections]]
text = ", trust in him"
verses = ""

[[sections]]
text = "alone, submit and subject my self unto him with all"
verses = ""

[[sections]]
text = "Humility, and"
verses = ""

[[sections]]
text = "Patience, look for all good things from him alone, and lastly with the entire Affection of my Heart"
verses = ""

[[sections]]
text = "love,"
verses = ""

[[sections]]
text = "reverence, and"
verses = ""

[[sections]]
text = "worship him, so that I am ready to renounce and forsake all Creatures rather"
verses = ""

[[sections]]
text = "than to commit the least thing that may be against his Will."
verses = "1 Corinthians 6:9,10; 1 Corinthians 10:7,14; Leviticus 19:31; Deuteronomy 18:11; Matthew 4:10; Apocalypse 19:10; Apocalypse 22:8,9; Job 17:3; Jeremiah 17:5; Hebrews 10:36; Colossians 1:11; Romans 5:3,4; 1 Corinthians 10:10; Philippians 2:14; 1 Peter 5:5,6; Psalm 10:4; Isaiah 45:7; John 1:17; Deuteronomy 6:5; Matthew 22:37; Deuteronomy 6:2; Psalm 111:10; Matthew 4:20; Matthew 5:29; Matthew 10:37,38"
