id = "107"
question = "What are good Works?"

[[sections]]
text = "Those only which are done by a"
verses = ""

[[sections]]
text = "true Faith, according"
verses = "Romans 14:23"

[[sections]]
text = "to God's Law, and are"
verses = "1 Samuel 15:22; Ephesians 2:10"

[[sections]]
text = "referred only to his Glory, and not those which are imagined by us as seeming to us to be right and good, or which"
verses = "1 Corinthians 10:31"

[[sections]]
text = "are delivered and commanded by Men."
verses = "Deuteronomy 11:32; Ezekiel 20:18,19; Isaiah 29:13; Matthew 15:9"
