id = "107"
question = "What is Idolatry?"

[[sections]]
text = "It is in Place of that one God, or besides that one true God who has manifested himself in his Word and Works, to make or imagine, and account any other thing wherein you repose your"
verses = ""

[[sections]]
text = "Hope and Confidence."
verses = "Philippians 3:19; Ephesians 5:5; Galatians 4:8; Ephesians 2:12; 1 John 2:23; John 5:23"
