id = "108"
question = "What is the second Commandment?"

[[sections]]
text = "You shall make to you no graven Image, nor the Likeness of any thing which is in Heaven above, or in the Earth beneath, nor in the Waters under the Earth: you shall not bow down to them, nor worship them, for I the Lord your God am a jealous God, and visit the sins of the Fathers upon the Children, unto the third and fourth Generation of them that hate me, and show Mercy to thousands of them which love me, and keep my Commandments."
verses = ""
