id = "113"
question = "What does God decree in the third Commandment?"

[[sections]]
text = "That not only by cursing"
verses = ""

[[sections]]
text = "or forswearing, but also by"
verses = "Leviticus 24:11; Leviticus 19:12"

[[sections]]
text = "rash swearing we should not use his Name despitefully, or unreverently, neither should by silence nor connivance be Partakers of these horrible Sins in others, but that"
verses = "Matthew 5:37; James 5:12"

[[sections]]
text = "we use the sacred and holy Name of God ever with great Devotion"
verses = ""

[[sections]]
text = "and Reverence, that he may be worshipped and honoured by us with a true and"
verses = "1 Timothy 2:8"

[[sections]]
text = "steadfast Confession"
verses = "Romans 2:24; 1 Timothy 6:1; Colossians 3:16,17"

[[sections]]
text = "and Invocation of his Name; and lastly, in all our Words and Actions whatsoever."
verses = "Matthew 10:32"
