id = "114"
question = "Is it then so grievous a Sin by swearing, or banning, to take the Name of God in vain, as that God is also angry with them who in as much as in them lies do not forbid or hinder it?"

[[sections]]
text = "Surely"
verses = ""

[[sections]]
text = "most grievous: for neither is there any Sin greater, or more offending God, than the despiting of his sacred Name; wherefore also he would have this Sin to be punished with Death."
verses = "Leviticus 5:1; Leviticus 24:15,16"
