id = "115"
question = "May a Man swear religiously and lawfully, by the Name of God?"

[[sections]]
text = "He may when as either the lawful Magistrate exacts it, or otherwise necessity requires it: by this means the Faith and Truth of any Man, or thing to be ratified and established, whereby both the Glory of God may be advanced, and the safety of others procured: for this kind of Swearing is"
verses = ""

[[sections]]
text = "ordained by God's Word, and therefore was well"
verses = "Deuteronomy 6:13; Deuteronomy 10:20; Isaiah 48:1; Hebrews 6:16"

[[sections]]
text = "used of the Fathers both in the old and new Testament."
verses = "Genesis 21:24; Genesis 31; Joshua 9:15,19; 2 Samuel 3:35; 1 Kings 1:29; Romans 1:9"
