id = "117"
question = "What does this second Commandment require?"

[[sections]]
text = "That we should not"
verses = ""

[[sections]]
text = "express or represent God by any Image or shape and figure, or worship him any otherwise then he has commanded himself in"
verses = "Deuteronomy 4:15; Isaiah 40:18; Romans 1:23; Acts 17:29"

[[sections]]
text = "his Word to be worshipped."
verses = "1 Samuel 15:23; Deuteronomy 12:30; Matthew 15:9"
