id = "117"
question = "What is the fourth Commandment?"

[[sections]]
text = "Remember that you keep holy the Sabbath Day: six Days shall you labor, and do all that you have to do, but the seventh Day is the Sabbath of the Lord your God, in it you shall do no manner of Work, You, nor your Son, nor your Daughter, your Man-Servant, nor your Maid-Servant, nor your Cattle, nor the Stranger that is within your Gates: for in six Days the Lord made Heaven, and Earth, the Sea, and all that in them is, and rested the seventh day, and hallowed it."
verses = ""
