id = "118"
question = "May there then at all any Images or Resemblances of things be made?"

[[sections]]
text = "God neither ought, nor can be represented by any means: and for the Creatures, although it be lawful to express them, yet God forbids notwithstanding their Images to be made or had, as thereby to worship or honour either them, or God by them:"
verses = "Exodus 23:24; Exodus 34:13,14,17; Numbers 33:52; Deuteronomy 7:5; Deuteronomy 12:13; Deuteronomy 16:22; 2 Kings 18:4"
