id = "119"
question = "But may not Images be tolerated in Churches, which may serve for Books unto the common People?"

[[sections]]
text = "No; for 'tis not seemly that we should be wiser then God, who will have his Church to"
verses = ""

[[sections]]
text = "be taught by the lively preaching of his Word, and not with"
verses = "2 Timothy 3:16,17; 2 Peter 1:19"

[[sections]]
text = "dumb Images."
verses = "Jeremiah 10:8; Habakkuk 2:18,19"
