id = "120"
question = "What does God enjoin us in the fifth Commandment?"

[[sections]]
text = "That we yield due honour, love, and faithfulness for our Parents, and so to all who bear Rule over us, and"
verses = ""

[[sections]]
text = "submit our selves with such obedience as is meet to their faithful Commandments and chastisements; and further also by that our patience"
verses = "Ephesians 6:1,2,5; Colossians 3:20,22,23,24; Ephesians 5:22; Proverbs 1:8; Proverbs 4:1; Proverbs 15:20; Proverbs 20:20; Exodus 21:17; Romans 13:1"

[[sections]]
text = "we bear and suffer their manners, ever thinking with our selves that God"
verses = "Proverbs 23:22; Genesis 9:25; 1 Peter 2:18"

[[sections]]
text = "will govern and guide us by their hand."
verses = "Ephesians 6:4,9; Galatians 3:19,21; Romans 13:1; Matthew 22:21"
