id = "122"
question = "Is it then so grievous a Sin by swearing, or cursing, to take the Name of God in vain, as that God is also angry with them who insofar as it lies within them do not forbid or hinder it?"

[[sections]]
text = "Surely"
verses = ""

[[sections]]
text = "most grievous: for neither is there any Sin greater, or more offending God, than the contempt of his sacred Name; therefore also he would have this Sin to be punished with Death."
verses = "Leviticus 5:1; Leviticus 24:15,16"
