id = "124"
question = "Is it lawful to swear by Saints, or other Creatures?"

[[sections]]
text = "No. For a lawful Oath is an Invocation of God, by which we desire that he, as the only searcher of Hearts, bear Witness unto the Truth, and punish the Swearer if he"
verses = ""

[[sections]]
text = "wittingly swear falsely: but this Honour"
verses = "2 Corinthians 1:23"

[[sections]]
text = "agrees to no Creature."
verses = "Matthew 5:33,34,35,36; James 5:12"
