id = "126"
question = "What is the meaning of the seventh Commandment?"

[[sections]]
text = "That God has"
verses = ""

[[sections]]
text = "in Execration all Turpitude and Filthiness, and therefore we also"
verses = "Leviticus 18:27,28"

[[sections]]
text = "must utterly hate, and detest it, and contrary-wise, live temperately, modestly, and"
verses = "Jude 22,23"

[[sections]]
text = "chastly, whether we"
verses = "1 Thessalonians 4:3,4"

[[sections]]
text = "live in holy Wedlock, or in single life."
verses = "Hebrews 13:4; 1 Corinthians 7:4"
