id = "129"
question = "What does God forbid in the eighth Commandment?"

[[sections]]
text = "Not only those"
verses = ""

[[sections]]
text = "Thefts and"
verses = "1 Corinthians 6:10"

[[sections]]
text = "Robberies, which the Magistrate punishes, but by the name of Theft he comprehends whatsoever Evil, Crafts, Fetches, and Devices, whereby we seek after other Mens Goods, and endeavour with force, or with some shew of Right, to"
verses = "1 Corinthians 5:10"

[[sections]]
text = "convey them over unto our selves; of which sort are"
verses = "Luke 3:14; 1 Thessalonians 4:6"

[[sections]]
text = "false Weights, false Ells"
verses = "Proverbs 11:1; Proverbs 16:11"

[[sections]]
text = "uneven Measures, deceitful Marchandize, counterfeit Coin,"
verses = "Ezekiel 45:9; Deuteronomy 25:13"

[[sections]]
text = "Usury, or any other way or means of furthering our Estate, which God has forbidden: to these we may add all"
verses = "Psalm 15:5; Luke 6:35"

[[sections]]
text = "Covetousness, and the manifold wast and"
verses = "1 Corinthians 6:10"

[[sections]]
text = "abusing of Gods Gifts."
verses = "Proverbs 5:15"
