id = "130"
question = "What does God exact in the sixth Commandment?"

[[sections]]
text = "That neither in thought nor in gesture, much less in deed, I reproach, or hate, or harm, or"
verses = ""

[[sections]]
text = "kill my Neighbour, either by myself, or by another, but cast away"
verses = "Matthew 5:21,22; Genesis 9:6; Matthew 26:52"

[[sections]]
text = "all desire of revenge; furthermore, that I hurt not myself, nor cast myself"
verses = "Ephesians 4:26; Romans 12:19; Matthew 18:35"

[[sections]]
text = "wittingly into any Danger. Therefore also, that Murder might not be committed, he"
verses = "Romans 13:14; Colossians 2:23; Matthew 4:7"

[[sections]]
text = "has armed the Magistrate with the Sword."
verses = "Genesis 9:6; Exodus 21:14; Matthew 26:52; Romans 13:4"
