id = "132"
question = "Is it enough then that we kill no Man, in such sort as has been said?"

[[sections]]
text = "No; for when God condemns Anger, Envy, Hatred, he requires that"
verses = ""

[[sections]]
text = "we love our Neighbour as ourselves and that we"
verses = "Matthew 22:39; Matthew 7:12"

[[sections]]
text = "use Humanity, Lenity, Courtesy, Patience,"
verses = "Romans 12:10; Ephesians 4:2; Galatians 6:1,2"

[[sections]]
text = "and Mercy towards him, and"
verses = "Galatians 6:1,2; Matthew 5:5; Romans 12:18; Matthew 5:7; Luke 6:36"

[[sections]]
text = "turn away from him as much as we may whatsoever may be hurtful unto him; in a word, that we be so affected in Mind as that we"
verses = "Exodus 23:5; Matthew 5:45; Romans 12:20"

[[sections]]
text = "stick not to do good also unto our Enemies."
verses = ""
