id = "132"
question = "What does the ninth Commandment exact?"

[[sections]]
text = "That I bear no"
verses = ""

[[sections]]
text = "false Witness against any Man,"
verses = "Proverbs 19:5,9; Proverbs 21:28; Psalm 15:3"

[[sections]]
text = "neither falsify any Man's words, neither backbite"
verses = "Romans 1:29,30"

[[sections]]
text = "nor reproach any Man, nor"
verses = "Matthew 7:1; Luke 6:37"

[[sections]]
text = "condemn any rashly, or unheard, but avoid, and"
verses = "John 8:44"

[[sections]]
text = "shun with all carefulness all kind of Lies, and Deceits, as the proper Works of the Devil, except I mean to stir"
verses = "Proverbs 12:22; Proverbs 13:5"

[[sections]]
text = "up against me the most grievous Wrath of God; and that in Judgments and other Affairs, I follow the Truth, and freely and constantly"
verses = ""

[[sections]]
text = "profess the matter as it indeed is, and moreover defend and increase as much as in me lies, the good Name and Estimation of others."
verses = "Ephesians 4:24; 1 Peter 4:8"
