id = "134"
question = "What does the tenth Commandment forbid?"

[[sections]]
text = "That our Hearts be not at any time moved by the least Desire or Cogitation against any Commandment of God, but"
verses = ""

[[sections]]
text = "that continually and from our Heart we detest all Sin, and contrarily delight in all Righteousness."
verses = "Romans 7:7"
