id = "135"
question = "Forbids God nothing else in this Commandment but actual Adultery, and such kinds of uncleanness?"

[[sections]]
text = "Yes, for since both our Body and Soul are the Temples of the Holy Ghost, God will have us to possess both in Purity and Holiness, and therefore Deeds,"
verses = ""

[[sections]]
text = "Gestures, Words,"
verses = "Ephesians 5:31; 1 Corinthians 6:18,20"

[[sections]]
text = "Thoughts, filthy Lusts, and whatsoever entices a Man unto these, all these God"
verses = "Matthew 5:27,28"

[[sections]]
text = "wholly forbids."
verses = "Ephesians 5:18; Job 31:1; Psalm 39:1"
