id = "136"
question = "Why will God then have his Law to be so exactly and severely preached seeing there is no Man in this life able to keep it?"

[[sections]]
text = "First, That all our life time we more & more"
verses = ""

[[sections]]
text = "acknowledge the great proneness of our Nature to Sin, and so much the more"
verses = "1 John 1:9; Psalm 22:5"

[[sections]]
text = "greedily desire remission of Sins, and Righteousness in Christ. Secondly, That we be doing of this always, and always thinking of it, and so implore and crave of the Father the"
verses = "Romans 7:24"

[[sections]]
text = "Grace of his Holy Spirit, whereby we may daily more and more be renewed to the Image and likeness of God, until at length after we are departed out of this life we may joyfully attain unto that Perfection which is promised unto us."
verses = "1 Corinthians 9:24; Philippians 3:12,13,14"
