id = "137"
question = "Wherefore is Prayer necessary for Christians?"

[[sections]]
text = "Because it is the chief part of that"
verses = ""

[[sections]]
text = "thankfulness which God requires of us, and also because God gives them only his Grace and Holy Spirit, who with unfeigned gronings beg them continually of him and"
verses = ""

[[sections]]
text = "yield him thanks for them."
verses = "Matthew 7:7,8; Luke 11:9,13; Matthew 13:12; Psalm 50:15"
