id = "138"
question = "What is required unto that Prayer which shall please God, and be heard of him?"

[[sections]]
text = "That we ask of the only true God, who has"
verses = ""

[[sections]]
text = "manifested himself in his Word, all things which he has commanded to be"
verses = "John 4:22"

[[sections]]
text = "asked of him with a true affection and desire of our Heart, and through an inward"
verses = "Romans 8:26; 1 John 5:14"

[[sections]]
text = "feeling of our need and"
verses = "John 4:23,24; Psalm 145:18"

[[sections]]
text = "misery cast our selves down prostrate in the presence of his Divine Majesty, and"
verses = "Psalm 2:11; Psalm 34:19; Isaiah 66:2"

[[sections]]
text = "build our selves on this sure foundation, that we though unworthy, yet for Christ's sake are"
verses = "Romans 10:14; Romans 8:15,16; James 1:6"

[[sections]]
text = "certainly heard of God, even as he has"
verses = ""

[[sections]]
text = "promised us in his Word."
verses = "John 14:13; John 15:16; John 16:23; Daniel 9:17,18,19; Psalm 7:7,8; Psalm 143:1"
