id = "138"
question = "What are those things which God here commands?"

[[sections]]
text = "That to my Power, I help and further the Welfare and Profit of my Neighbour, and that I so deal with him as I would desire to be dealt with myself, and that I do my own Work plainly and faithfully, that I may thereby help others who are distressed with any need or Calamity."
verses = "Matthew 7:12; Ephesians 4:28"
