id = "143"
question = "But can they who are converted to God, perfectly observe, and keep these Commandments?"

[[sections]]
text = "No, but even the holiest Men as long they live, have only small Beginnings of"
verses = ""

[[sections]]
text = "this Obedience, yet so that they"
verses = "Romans 7:14,15; Ecclesiastes 7:22"

[[sections]]
text = "begin with a sincere and earnest desire and endeavour to live not according to some only, but according to all the Commandments of God."
verses = "Romans 7:22; James 2:10"
