id = "144"
question = "What is the first Petition?"

[[sections]]
text = "Hallowed be thy Name; that is, grant us, first to"
verses = ""

[[sections]]
text = "know thee right, and worship, praise,"
verses = "John 17:3; Jeremiah 9:23,24; Jeremiah 31:33,34; Matthew 16:17; James 1:5; Psalm 119:105"

[[sections]]
text = "and magnify thy Almightiness, Goodness, Justice, Mercy and Truth, shining in all thy Works; and further also to direct our whole Life, Thoughts, Words, and Works to this end, that thy most Holy Name be not reproach'd by us, but rather be"
verses = "Psalm 119:137,138; Luke 1:45,46; Psalm 145:8,9,17; Exodus 34:5,6,7; Psalm 143:1,2,5,10,11,12; Jeremiah 31:3; Jeremiah 32:18,19,40,41; Jeremiah 33:11,20; Matthew 19:17; Romans 3:3,4; Romans 11:22,23; 2 Timothy 2:19"

[[sections]]
text = "renowned with Honour, and Praises."
verses = "Psalm 115:1; Psalm 71:8"
