id = "145"
question = "What is the second Petition?"

[[sections]]
text = "Thy Kingdom come; that is, rule for us so by thy Word and Spirit, that we may"
verses = ""

[[sections]]
text = "humble and Submit our selves more and more unto thee. Also preserve and increase thy"
verses = "Matthew 6:33; Psalm 119:5; Psalm 143:10"

[[sections]]
text = "Church; destroy the Works of the Devil, and all Power that lifts up it self against thy Majesty; make all those Councils frustrate, and void, which are"
verses = "Psalm 122:6,7"

[[sections]]
text = "taken against thy Word, until at length thou"
verses = "Psalm 51:18; 1 John 3:8; Romans 16:20"

[[sections]]
text = "reign fully and perfectly, when thou shalt be all"
verses = "Apocalypse 22:17,20; Romans 8:22,23"

[[sections]]
text = "in all."
verses = "1 Corinthians 15:28"
