id = "147"
question = "What is the fourth Petition?"

[[sections]]
text = "Give us this Day our daily bread; that is, give unto us all things which"
verses = ""

[[sections]]
text = "are needful for this Life, that by them we may acknowledg and confess thee to be the only Fountain from whence all good things flow; and all our Care and Industry, and even thine own Gifts to be unfortunate"
verses = "Psalm 145:15,16; Psalm 104:4; Matthew 6:25"

[[sections]]
text = "and noisom unto us except thou bless them; wherefore grant that turning our Trust away from all Creatures, we"
verses = "Acts 17:27,28; Acts 14:16,17; 1 Corinthians 15:58; Deuteronomy 8:3; Psalm 27:13"

[[sections]]
text = "place and repose it in thee alone."
verses = "Psalm 62:11"
