id = "149"
question = "What is the sixth Petition?"

[[sections]]
text = "Lead us not into Temptation, but deliver us from Evil. That is, because we our selves, are so feeble and weak by Nature, that"
verses = ""

[[sections]]
text = "we cannot stand so much as one Moment or Instant; and our most deadly Enemies"
verses = "John 15:5; Psalm 103:14"

[[sections]]
text = "Satan, the"
verses = "1 Peter 5:8; Ephesians 6:12"

[[sections]]
text = "World, and our own"
verses = "John 15:19"

[[sections]]
text = "Flesh do incessantly oppugne and assault us, uphold thou us, and establish and strengthen us by the might of thy Spirit, that we may not in this spiritual"
verses = "Romans 7:23; Galatians 5:17"

[[sections]]
text = "Combat yield as vanquished, but may so long stoutly withstand them, until at length"
verses = "Matthew 26:41; Mark 13:33"

[[sections]]
text = "we get the full and perfect Victory."
verses = "1 Thessalonians 3:13; 1 Thessalonians 5:23"
