id = "150"
question = "How concludest thou this Prayer?"

[[sections]]
text = "For thine is the Kingdom, the Power, and the Glory for ever. That is, we ask and crave all these things of thee, because seeing both thou art our King, and art Almighty, thou art both willing and able"
verses = ""

[[sections]]
text = "to give them all unto us; and these things we therefore ask, that out of them, not unto us, but unto thy holy Name all Glory"
verses = "Romans 10:11,12; 2 Peter 2:9"

[[sections]]
text = "may redound."
verses = "Psalm 115:1; Jeremiah 33:8,9"
