id = "150"
question = "Why does Christ teach us to call God our Father?"

[[sections]]
text = "That immediately, at the very Entrance and Beginning of the Prayer, he might stir up in us such a Reverence, and Confidence of God as is meet for the Sons of God, which must be the ground and foundation of our Prayer, namely, that God through Christ is made our"
verses = ""

[[sections]]
text = "Father, and will much less deny us these things which we ask of him with a true Faith, than our earthly Parents deny unto us earthly things."
verses = "Matthew 7:9,10; Luke 11:11"
