id = "151"
question = "What meaneth this Particle, Amen?"

[[sections]]
text = "That the thing is sure, and out of doubt; for my Prayer is much more certainly heard of God, than I feel in my Heart that I unfeignedly"
verses = ""

[[sections]]
text = "desire the same."
verses = "2 Corinthians 1:20; 2 Timothy 2:13"
