id = "151"
question = "Why is that added, which art in Heaven?"

[[sections]]
text = "That we"
verses = ""

[[sections]]
text = "conceive not basely nor terrenly of God's Heavenly Majesty, and also that we"
verses = "Jeremiah 23:24; Acts 17:24,25,27"

[[sections]]
text = "look for, and expect from his Omnipotency whatsoever things are necessary for our Soul and Body."
verses = "Romans 10:12"
