id = "154"
question = "What is the third Petition?"

[[sections]]
text = "Thy Will be done in Earth, as it is in Heaven. That is, grant that we, and all Men, renouncing"
verses = ""

[[sections]]
text = "and forsaking our own Will, may readily, and without any"
verses = "Matthew 16:24; Titus 2:12"

[[sections]]
text = "grudging, obey thy Will, which is only holy; and that so every one of us may"
verses = "Luke 22:42"

[[sections]]
text = "faithfully perform that Duty and Charge which thou has committed unto us, even as the blessed Angels do"
verses = "1 Corinthians 7:24"

[[sections]]
text = "in Heaven."
verses = "Psalm 103:20,21"
