id = "155"
question = "What is the fourth Petition?"

[[sections]]
text = "Give us this Day our daily bread; that is, give unto us all things which"
verses = ""

[[sections]]
text = "are needful for this Life, that by them we may acknowledge and confess thee to be the only Fountain from whence all good things flow; and all our Care and Industry, and even your own Gifts to be unprofitable"
verses = "Psalm 145:15,16; Psalm 104:4; Matthew 6:25"

[[sections]]
text = "and harmful unto us unless you bless them; therefore grant that turning our Trust away from all Creatures, we"
verses = "Acts 17:27,28; Acts 14:16,17; 1 Corinthians 15:58; Deuteronomy 8:3; Psalm 27:13"

[[sections]]
text = "place and rest it in thee alone."
verses = "Psalm 62:11"
