id = "156"
question = "What is the fifth Petition?"

[[sections]]
text = "Forgive us our Trespasses, as we forgive them that trespass against us. That is, even for the Blood of Christ do not"
verses = ""

[[sections]]
text = "impute unto us most miserable and wretched sinners all our Offences, neither that Corruption which still clings unto us, even as we also feel this Testimony of thy Grace in our Hearts, that we steadfastly purpose sincerely from"
verses = "Psalm 51:1; Psalm 143:2"

[[sections]]
text = "our Hearts, to pardon and forgive all those who have offended us."
verses = "Matthew 6:14"
