id = "159"
question = "What does this word Amen mean?"

[[sections]]
text = "That the thing is sure, and out of doubt; for my Prayer is much more certainly heard of God, than I feel in my Heart that I sincerely"
verses = ""

[[sections]]
text = "desire this."
verses = "2 Corinthians 1:20; 2 Timothy 2:13"
